name: cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
# continuous integration job
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  # use to shorten the commit SHA for tagging the Docker image
      - name: Set short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::6}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: kesarikumaran/python-app:${{ steps.vars.outputs.short_sha }}

# continuous deployment job
  cd:
    needs: ci
    runs-on: self-hosted
    steps:
    # need to install argocd cli inorder to connect to the argocd server for deployment
      - name: Install ArgoCD
        shell: bash
        run: |
          curl -ksSL -o argocd http://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /use/local/bin/argocd
    
    # this needs will create a dependency on the ci job. (like after ci cd must be performed)
      - name: ArgoCD app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd --insecure --grpc-web --username admin --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app